apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rdc
  name: rdc
  namespace: default
spec:
  containers:
  - image: crystalline407/rdc:0.0.1
    imagePullPolicy: Always
    name: rdc
  nodeSelector:
    agentpool: win1
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Exists
